'use strict';

// Run with: node --test tests/test_passkey_frontend.js
// A small DOM harness exercises the shipped script with controllable promises.
// It makes no network requests and never invokes a real authenticator.
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const source = fs.readFileSync(path.join(__dirname, '../static/passkey-auth.js'), 'utf8');
const CALLBACK = 'https://bvfndgjiahjqdlnyygnx.supabase.co/auth/v1/callback?code=test-code&state=test-state';

function deferred() {
  let resolve, reject;
  const promise = new Promise((yes, no) => { resolve = yes; reject = no; });
  return { promise, resolve, reject };
}

async function until(predicate, description) {
  // Drain only microtasks generated by the controlled async work. No wall-clock
  // sleeps or dependency on the production script's chosen timeout durations.
  for (let step = 0; step < 100; step += 1) {
    if (predicate()) return;
    await Promise.resolve();
  }
  assert.fail('Async state was not reached: ' + description);
}

function encoded(text) { return Buffer.from(text).toString('base64url'); }
function bytes(text) { return new Uint8Array(Buffer.from(text)); }

function publicOptions(mode, sequence) {
  const result = { challenge: encoded('challenge-' + sequence), timeout: 60000 };
  if (mode === 'signup') {
    Object.assign(result, {
      rp: { id: 'investment-bot-ta24.onrender.com', name: '経済NEWS' },
      user: { id: encoded('0123456789abcdef'), name: 'test-account', displayName: 'Test' },
      pubKeyCredParams: [{ type: 'public-key', alg: -7 }],
      authenticatorSelection: { residentKey: 'required', userVerification: 'required' },
      excludeCredentials: [],
    });
  } else {
    Object.assign(result, { rpId: 'investment-bot-ta24.onrender.com', userVerification: 'required', allowCredentials: [] });
  }
  return result;
}

function credential(mode) {
  const response = { clientDataJSON: bytes('client-data') };
  if (mode === 'signup') {
    response.attestationObject = bytes('attestation');
    response.getTransports = () => ['internal'];
  } else {
    Object.assign(response, {
      authenticatorData: bytes('authenticator-data'), signature: bytes('signature'),
      userHandle: bytes('0123456789abcdef'),
    });
  }
  return {
    id: encoded('credential-id'), rawId: bytes('credential-id'), type: 'public-key',
    authenticatorAttachment: 'platform', getClientExtensionResults: () => ({}), response,
  };
}

function harness(mode = 'login') {
  let now = 1_000_000;
  const listeners = new Map();
  const requests = [], nativeCalls = [], redirects = [];
  const initialLabel = mode === 'signup' ? 'パスキーを作成して無料登録' : 'パスキーでログイン';
  const button = {
    textContent: initialLabel, disabled: true,
    addEventListener(name, callback) { listeners.set(name, callback); },
  };
  const message = { textContent: '準備しています…', className: 'kna-msg' };
  const document = {
    body: { dataset: { mode } }, documentElement: { style: { setProperty() {} } },
    querySelectorAll() { return []; },
    querySelector(selector) {
      assert.equal(selector, 'meta[name="csrf-token"]');
      return { content: 'csrf-for-test' };
    },
    getElementById(id) {
      if (id === 'passkeyStart') return button;
      if (id === 'passkeyMessage') return message;
      assert.fail('Unexpected DOM lookup: ' + id);
    },
  };
  function native(method, options) {
    const pending = deferred();
    nativeCalls.push({ method, options, ...pending });
    return pending.promise;
  }
  const context = {
    document, Uint8Array, URL, console,
    Date: class extends Date { static now() { return now; } },
    localStorage: { getItem() { return null; } },
    PublicKeyCredential: function PublicKeyCredential() {},
    navigator: { credentials: { create: options => native('create', options), get: options => native('get', options) } },
    location: { assign(url) { redirects.push(url); } },
    atob: value => Buffer.from(value, 'base64').toString('binary'),
    btoa: value => Buffer.from(value, 'binary').toString('base64'),
    fetch(url, init) {
      const pending = deferred();
      requests.push({ url, init, ...pending });
      return pending.promise;
    },
  };
  context.window = context;
  vm.runInNewContext(source, context, { filename: 'passkey-auth.js' });
  return {
    mode, button, message, requests, nativeCalls, redirects, initialLabel,
    advanceIdleHour() { now += 60 * 60 * 1000; },
    // Direct dispatch also models an already-queued duplicate event. This makes
    // the busy guard observable independently of disabled-button DOM behavior.
    click() { return listeners.get('click')({ type: 'click' }); },
    respond(index, data, status = 200) {
      assert.ok(requests[index], 'Expected request ' + index);
      requests[index].resolve({ ok: status >= 200 && status < 300, status, json: async () => data });
    },
    respondOptions(index) {
      assert.match(requests[index].url, /\/options$/);
      this.respond(index, publicOptions(mode, index));
    },
    async ready() {
      assert.equal(requests.length, 1, 'Page load should prefetch exactly once');
      this.respondOptions(0);
      await until(() => !button.disabled, 'initial options ready');
      assert.equal(button.textContent, initialLabel);
    },
    async completeNative(index, callback = CALLBACK) {
      const before = requests.length;
      nativeCalls[index].resolve(credential(mode));
      await until(() => requests.length === before + 1, 'verification request');
      const verification = requests.at(-1);
      assert.match(verification.url, /\/verify$/);
      this.respond(requests.length - 1, { redirect_url: callback });
      return verification;
    },
  };
}

for (const mode of ['login', 'signup']) {
  test(mode + ': ready first click invokes native synchronously and verifies before redirect', async () => {
    const app = harness(mode);
    await app.ready();
    const click = app.click();
    // No awaiting/microtask drain before this assertion: the real click's
    // activation must reach native WebAuthn immediately when options are ready.
    assert.equal(app.nativeCalls.length, 1);
    assert.equal(app.nativeCalls[0].method, mode === 'signup' ? 'create' : 'get');
    assert.ok(app.nativeCalls[0].options.publicKey.challenge instanceof Uint8Array);
    assert.equal(app.button.disabled, true);
    assert.deepEqual(app.redirects, []);
    const verification = await app.completeNative(0);
    assert.equal(verification.url, '/auth/passkey/' + (mode === 'signup' ? 'registration' : 'authentication') + '/verify');
    assert.equal(verification.init.method, 'POST');
    assert.equal(verification.init.credentials, 'same-origin');
    assert.equal(verification.init.headers['X-CSRF-Token'], 'csrf-for-test');
    const sent = JSON.parse(verification.init.body).credential;
    assert.equal(sent.rawId, encoded('credential-id'));
    assert.equal(sent.response.clientDataJSON, encoded('client-data'));
    if (mode === 'signup') {
      assert.equal(sent.response.attestationObject, encoded('attestation'));
    } else {
      assert.equal(sent.response.userHandle, encoded('0123456789abcdef'));
    }
    await click;
    assert.deepEqual(app.redirects, [CALLBACK]);
    assert.equal(app.button.disabled, true, 'Keep the button disabled while navigation is leaving');
    await app.click();
    assert.equal(app.nativeCalls.length, 1, 'A queued click during redirect must not create another ceremony');
    assert.equal(app.requests.length, 2, 'A queued click during redirect must not fetch new options');
  });

  test(mode + ': cancellation prepares automatically, then one retry click invokes native', async () => {
    const app = harness(mode);
    await app.ready();
    const firstClick = app.click();
    const cancelled = new Error('test cancellation');
    cancelled.name = 'NotAllowedError';
    app.nativeCalls[0].reject(cancelled);
    await until(() => app.requests.length === 2, 'automatic preparation after cancellation');
    assert.equal(app.button.disabled, true);
    assert.match(app.message.textContent, /認証.*完了しませんでした/);
    assert.ok(app.requests.every(request => request.url.endsWith('/options')), 'Cancelled native ceremony must not verify');
    await app.click();
    assert.equal(app.requests.length, 2, 'Queued retry must share preparation');
    assert.equal(app.nativeCalls.length, 1);
    app.respondOptions(1);
    await firstClick;
    assert.equal(app.button.disabled, false);
    assert.equal(app.button.textContent, app.initialLabel);
    assert.match(app.message.textContent, /認証.*完了しませんでした/, 'Keep the explanatory error visible after preparing');
    const retryClick = app.click();
    assert.equal(app.nativeCalls.length, 2, 'The next single click must launch WebAuthn synchronously');
    await app.completeNative(1);
    await retryClick;
    assert.deepEqual(app.redirects, [CALLBACK]);
  });

  test(mode + ': stale options refresh and invoke native within the same click', async () => {
    const app = harness(mode);
    await app.ready();
    app.advanceIdleHour();
    const click = app.click();
    assert.equal(app.requests.length, 2);
    assert.equal(app.button.disabled, true);
    assert.equal(app.nativeCalls.length, 0);
    await app.click();
    assert.equal(app.requests.length, 2, 'A second queued click must not start another refresh');
    app.respondOptions(1);
    await until(() => app.nativeCalls.length === 1, 'native call after stale option refresh');
    assert.equal(app.button.disabled, true);
    assert.deepEqual(Array.from(app.nativeCalls[0].options.publicKey.challenge), Array.from(Buffer.from('challenge-1')));
    await app.completeNative(0);
    await click;
    assert.deepEqual(app.redirects, [CALLBACK]);
  });

  test(mode + ': initial preparation failure recovers with one retry click', async () => {
    const app = harness(mode);
    app.respond(0, { error: '準備に失敗しました' }, 503);
    await until(() => !app.button.disabled, 'failed initial preparation settled');
    assert.match(app.message.textContent, /準備に失敗しました/);
    const retry = app.click();
    assert.equal(app.requests.length, 2);
    assert.equal(app.button.disabled, true);
    app.respondOptions(1);
    await until(() => app.nativeCalls.length === 1, 'native call after successful retry preparation');
    await app.completeNative(0);
    await retry;
    assert.deepEqual(app.redirects, [CALLBACK]);
  });
}

test('double clicks during a native ceremony do not duplicate native or verification calls', async () => {
  const app = harness();
  await app.ready();
  const first = app.click();
  const duplicate = app.click();
  assert.equal(app.nativeCalls.length, 1);
  assert.equal(app.requests.length, 1);
  assert.equal(app.button.disabled, true);
  await app.completeNative(0);
  await Promise.all([first, duplicate]);
  assert.equal(app.requests.filter(request => request.url.endsWith('/verify')).length, 1);
  assert.deepEqual(app.redirects, [CALLBACK]);
});

test('clicks queued during initial preparation reuse the in-flight options request', async () => {
  const app = harness();
  const first = app.click();
  const duplicate = app.click();
  assert.equal(app.requests.length, 1);
  assert.equal(app.nativeCalls.length, 0);
  app.respondOptions(0);
  await until(() => app.nativeCalls.length === 1, 'native call after shared initial preparation');
  await app.completeNative(0);
  await Promise.all([first, duplicate]);
  assert.equal(app.requests.filter(request => request.url.endsWith('/options')).length, 1);
});

test('verification failure prepares fresh options without redirect and preserves the error', async () => {
  const app = harness();
  await app.ready();
  const click = app.click();
  app.nativeCalls[0].resolve(credential('login'));
  await until(() => app.requests.length === 2, 'verification request');
  app.respond(1, { error: 'サーバーで認証を確認できませんでした' }, 400);
  await until(() => app.requests.length === 3, 'preparation following verification failure');
  assert.deepEqual(app.redirects, []);
  assert.equal(app.button.disabled, true);
  assert.match(app.message.textContent, /サーバーで認証を確認できませんでした/);
  app.respondOptions(2);
  await click;
  assert.equal(app.button.disabled, false);
  assert.match(app.message.textContent, /サーバーで認証を確認できませんでした/);
  const retry = app.click();
  assert.equal(app.nativeCalls.length, 2);
  await app.completeNative(1);
  await retry;
  assert.deepEqual(app.redirects, [CALLBACK]);
});

test('failed automatic preparation leaves a usable one-click recovery', async () => {
  const app = harness();
  await app.ready();
  const click = app.click();
  const cancelled = new Error('cancelled');
  cancelled.name = 'NotAllowedError';
  app.nativeCalls[0].reject(cancelled);
  await until(() => app.requests.length === 2, 'automatic options request');
  app.respond(1, { error: '準備に失敗しました' }, 503);
  await click;
  assert.equal(app.button.disabled, false);
  const retry = app.click();
  assert.equal(app.requests.length, 3);
  app.respondOptions(2);
  await until(() => app.nativeCalls.length === 2, 'native call on a retry after preparation failure');
  await app.completeNative(1);
  await retry;
  assert.deepEqual(app.redirects, [CALLBACK]);
});

for (const callback of [
  'https://attacker.example/auth/v1/callback?code=wrong',
  'https://bvfndgjiahjqdlnyygnx.supabase.co/other-path?code=wrong',
  'http://bvfndgjiahjqdlnyygnx.supabase.co/auth/v1/callback?code=wrong',
  'javascript:alert(1)',
]) {
  test('successful verification cannot redirect outside the callback allowlist: ' + callback.split('?')[0], async () => {
    const app = harness();
    await app.ready();
    const click = app.click();
    await app.completeNative(0, callback);
    await until(() => app.requests.length === 3, 'fresh options after rejecting callback URL');
    assert.deepEqual(app.redirects, []);
    app.respondOptions(2);
    await click;
    assert.deepEqual(app.redirects, []);
    assert.equal(app.button.disabled, false);
  });
}
