'use strict';

// Run with: node --test tests/test_passkey_frontend.js
// A small DOM harness exercises the shipped script with controllable promises.
// It makes no network requests and never invokes a real authenticator.
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const source = fs.readFileSync(path.join(__dirname, '../static/passkey-auth.js'), 'utf8');
const SITE = 'https://investment-bot-ta24.onrender.com';
const CALLBACK = 'https://bvfndgjiahjqdlnyygnx.supabase.co/auth/v1/callback?code=test-code&state=test-state';

function deferred() {
  let resolve, reject;
  const promise = new Promise((yes, no) => { resolve = yes; reject = no; });
  return { promise, resolve, reject };
}

async function until(predicate, description) {
  // Drain only microtasks generated by the controlled async work. No wall-clock
  // sleeps or dependency on the production script's chosen timeout durations.
  for (let step = 0; step < 100; step += 1) {
    if (predicate()) return;
    await Promise.resolve();
  }
  assert.fail('Async state was not reached: ' + description);
}

function encoded(text) { return Buffer.from(text).toString('base64url'); }
function bytes(text) { return new Uint8Array(Buffer.from(text)); }

function publicOptions(mode, sequence) {
  const result = { challenge: encoded('challenge-' + sequence), timeout: 60000 };
  if (mode === 'signup') {
    Object.assign(result, {
      rp: { id: 'investment-bot-ta24.onrender.com', name: '経済NEWS' },
      user: { id: encoded('0123456789abcdef'), name: 'test-account', displayName: 'Test' },
      pubKeyCredParams: [{ type: 'public-key', alg: -7 }],
      authenticatorSelection: { residentKey: 'required', userVerification: 'required' },
      excludeCredentials: [],
    });
  } else {
    Object.assign(result, { rpId: 'investment-bot-ta24.onrender.com', userVerification: 'required', allowCredentials: [] });
  }
  return result;
}

function credential(mode) {
  const response = { clientDataJSON: bytes('client-data') };
  if (mode === 'signup') {
    response.attestationObject = bytes('attestation');
    response.getTransports = () => ['internal'];
  } else {
    Object.assign(response, {
      authenticatorData: bytes('authenticator-data'), signature: bytes('signature'),
      userHandle: bytes('0123456789abcdef'),
    });
  }
  return {
    id: encoded('credential-id'), rawId: bytes('credential-id'), type: 'public-key',
    authenticatorAttachment: 'platform', getClientExtensionResults: () => ({}), response,
  };
}

function harness(mode = 'login', intent = mode, config = {}) {
  let now = 1_000_000;
  let nextTimer = 1;
  const timers = new Map();
  const listeners = new Map();
  const newListeners = new Map();
  const documentListeners = new Map();
  const requests = [], nativeCalls = [], redirects = [];
  const initialLabel = mode === 'signup' ? 'パスキーを作成して無料登録' : intent === 'signup' ? '保存したパスキーでログイン' : 'パスキーでログイン';
  const button = {
    textContent: initialLabel, disabled: true,
    hidden: mode === 'login' && intent === 'signup',
    addEventListener(name, callback) { listeners.set(name, callback); },
  };
  const messageHistory = ['準備しています…'];
  const message = {
    className: 'kna-msg',
    get textContent() { return messageHistory.at(-1); },
    set textContent(value) { messageHistory.push(value); },
  };
  const title = { textContent: mode === 'signup' || intent === 'signup' ? 'アカウント作成' : 'おかえりなさい' };
  const introHistory = ['保存済みのパスキーで続きから再開できます。'];
  const intro = {
    hidden: mode === 'login' && intent === 'signup',
    style: {},
    get textContent() { return introHistory.at(-1); },
    set textContent(value) { introHistory.push(value); },
  };
  const sections = Object.fromEntries(['passkeyNewSection', 'passkeyHelp', 'passkeyFooter'].map(id => [id, { hidden: false }]));
  let navigationFailures = config.navigationFailures || 0;
  const newButton = mode === 'login' && intent === 'signup' ? {
    disabled: true,
    dataset: { url: config.newURL || '/auth/passkey/authorize?screen_hint=signup_new&state=active-state&code_challenge=active-challenge' },
    addEventListener(name, callback) { newListeners.set(name, callback); },
  } : null;
  const document = {
    body: { dataset: { mode, intent } }, documentElement: { style: { setProperty() {} } },
    visibilityState: 'visible',
    addEventListener(name, callback) {
      if (!documentListeners.has(name)) documentListeners.set(name, new Set());
      documentListeners.get(name).add(callback);
    },
    removeEventListener(name, callback) { documentListeners.get(name)?.delete(callback); },
    querySelectorAll() { return []; },
    querySelector(selector) {
      assert.equal(selector, 'meta[name="csrf-token"]');
      return { content: 'csrf-for-test' };
    },
    getElementById(id) {
      if (id === 'passkeyStart') return button;
      if (id === 'passkeyMessage') return message;
      if (id === 'passkeyNew') return newButton;
      if (id === 'knaTitle') return title;
      if (id === 'passkeyIntro') return intro;
      if (sections[id]) return sections[id];
      assert.fail('Unexpected DOM lookup: ' + id);
    },
  };
  function native(method, options) {
    const pending = deferred();
    nativeCalls.push({ method, options, ...pending });
    return pending.promise;
  }
  const context = {
    document, Uint8Array, URL, console, AbortController,
    Date: class extends Date { static now() { return now; } },
    setTimeout(callback, delay, ...args) {
      const id = nextTimer++;
      timers.set(id, { at: now + delay, delay, callback: () => callback(...args) });
      return id;
    },
    clearTimeout(id) { timers.delete(id); },
    localStorage: { getItem() { return null; } },
    PublicKeyCredential: config.supported === false ? undefined : function PublicKeyCredential() {},
    navigator: { credentials: { create: options => native('create', options), get: options => native('get', options) } },
    location: { origin: SITE, href: SITE + '/auth/passkey/authorize', assign(url) {
      if (navigationFailures-- > 0) throw new Error('Navigation interrupted');
      redirects.push(url);
    } },
    atob: value => Buffer.from(value, 'base64').toString('binary'),
    btoa: value => Buffer.from(value, 'binary').toString('base64'),
    fetch(url, init) {
      const pending = deferred();
      const request = { url, init, ...pending, jsonPending: null, jsonReadStarted: false };
      if (init.signal) {
        const abort = () => {
          const error = new Error('Test request aborted');
          error.name = 'AbortError';
          pending.reject(error);
          if (request.jsonPending) request.jsonPending.reject(error);
        };
        if (init.signal.aborted) abort();
        else init.signal.addEventListener('abort', abort, { once: true });
      }
      requests.push(request);
      return pending.promise;
    },
  };
  context.window = context;
  vm.runInNewContext(source, context, { filename: 'passkey-auth.js' });
  return {
    mode, intent, button, newButton, message, messageHistory, title, intro, introHistory, sections, requests, nativeCalls, redirects, initialLabel, timers, documentListeners,
    advanceIdleHour() { now += 60 * 60 * 1000; },
    setVisibility(value) {
      document.visibilityState = value;
      for (const callback of documentListeners.get('visibilitychange') || []) callback({ type: 'visibilitychange' });
    },
    advanceTimersBy(duration) {
      now += duration;
      for (const [id, timer] of [...timers].sort((left, right) => left[1].at - right[1].at)) {
        if (timer.at > now) break;
        timers.delete(id);
        timer.callback();
      }
    },
    expireNextTimer() {
      assert.ok(timers.size > 0, 'Expected a pending request deadline');
      const [id, timer] = [...timers].sort((left, right) => left[1].at - right[1].at)[0];
      now = timer.at;
      timers.delete(id);
      timer.callback();
    },
    // Direct dispatch also models an already-queued duplicate event. This makes
    // the busy guard observable independently of disabled-button DOM behavior.
    click() { return listeners.get('click')({ type: 'click' }); },
    clickNew() { assert.ok(newButton); return newListeners.get('click')({ type: 'click' }); },
    respond(index, data, status = 200) {
      assert.ok(requests[index], 'Expected request ' + index);
      requests[index].resolve({ ok: status >= 200 && status < 300, status, json: async () => {
        requests[index].jsonReadStarted = true;
        return data;
      } });
    },
    respondWithPendingJSON(index, status = 200) {
      const request = requests[index];
      assert.ok(request, 'Expected request ' + index);
      request.jsonPending = deferred();
      request.resolve({ ok: status >= 200 && status < 300, status, json: () => {
        request.jsonReadStarted = true;
        return request.jsonPending.promise;
      } });
      return request.jsonPending;
    },
    respondOptions(index) {
      assert.match(requests[index].url, /\/options$/);
      this.respond(index, publicOptions(mode, index));
    },
    async ready() {
      assert.equal(requests.length, 1, 'Page load should prefetch exactly once');
      this.respondOptions(0);
      await until(() => !button.disabled, 'initial options ready');
      assert.equal(button.textContent, initialLabel);
      assert.equal(timers.size, 0, 'Preparation must release its deadline when ready');
    },
    async completeNative(index, callback = CALLBACK) {
      const before = requests.length;
      nativeCalls[index].resolve(credential(mode));
      await until(() => requests.length === before + 1, 'verification request');
      const verification = requests.at(-1);
      assert.match(verification.url, /\/verify$/);
      this.respond(requests.length - 1, { redirect_url: callback });
      return verification;
    },
  };
}

for (const mode of ['login', 'signup']) {
  test(mode + ': ready first click invokes native synchronously and verifies before redirect', async () => {
    const app = harness(mode);
    await app.ready();
    const click = app.click();
    // No awaiting/microtask drain before this assertion: the real click's
    // activation must reach native WebAuthn immediately when options are ready.
    assert.equal(app.nativeCalls.length, 1);
    assert.equal(app.nativeCalls[0].method, mode === 'signup' ? 'create' : 'get');
    assert.ok(app.nativeCalls[0].options.publicKey.challenge instanceof Uint8Array);
    assert.equal(app.button.disabled, true);
    assert.deepEqual(app.redirects, []);
    const verification = await app.completeNative(0);
    assert.equal(verification.url, '/auth/passkey/' + (mode === 'signup' ? 'registration' : 'authentication') + '/verify');
    assert.equal(verification.init.method, 'POST');
    assert.equal(verification.init.credentials, 'same-origin');
    assert.equal(verification.init.headers['X-CSRF-Token'], 'csrf-for-test');
    const sent = JSON.parse(verification.init.body).credential;
    assert.equal(sent.rawId, encoded('credential-id'));
    assert.equal(sent.response.clientDataJSON, encoded('client-data'));
    if (mode === 'signup') {
      assert.equal(sent.response.attestationObject, encoded('attestation'));
    } else {
      assert.equal(sent.response.userHandle, encoded('0123456789abcdef'));
    }
    await click;
    assert.deepEqual(app.redirects, [CALLBACK]);
    assert.equal(app.timers.size, 0, 'Ordinary login and explicit signup have no extra announcement delay');
    assert.ok(app.introHistory.every(text => !text.includes('アカウントが見つかりました')));
    assert.equal(app.button.disabled, true, 'Keep the button disabled while navigation is leaving');
    await app.click();
    assert.equal(app.nativeCalls.length, 1, 'A queued click during redirect must not create another ceremony');
    assert.equal(app.requests.length, 2, 'A queued click during redirect must not fetch new options');
  });

  test(mode + ': cancellation prepares automatically, then one retry click invokes native', async () => {
    const app = harness(mode);
    await app.ready();
    const firstClick = app.click();
    const cancelled = new Error('test cancellation');
    cancelled.name = 'NotAllowedError';
    app.nativeCalls[0].reject(cancelled);
    await until(() => app.requests.length === 2, 'automatic preparation after cancellation');
    assert.equal(app.button.disabled, true);
    assert.match(app.message.textContent, /認証.*完了しませんでした/);
    assert.ok(app.requests.every(request => request.url.endsWith('/options')), 'Cancelled native ceremony must not verify');
    await app.click();
    assert.equal(app.requests.length, 2, 'Queued retry must share preparation');
    assert.equal(app.nativeCalls.length, 1);
    app.respondOptions(1);
    await firstClick;
    assert.equal(app.button.disabled, false);
    assert.equal(app.button.textContent, app.initialLabel);
    assert.match(app.message.textContent, /認証.*完了しませんでした/, 'Keep the explanatory error visible after preparing');
    const retryClick = app.click();
    assert.equal(app.nativeCalls.length, 2, 'The next single click must launch WebAuthn synchronously');
    await app.completeNative(1);
    await retryClick;
    assert.deepEqual(app.redirects, [CALLBACK]);
  });

  test(mode + ': stale options refresh and invoke native within the same click', async () => {
    const app = harness(mode);
    await app.ready();
    app.advanceIdleHour();
    const click = app.click();
    assert.equal(app.requests.length, 2);
    assert.equal(app.button.disabled, true);
    assert.equal(app.nativeCalls.length, 0);
    await app.click();
    assert.equal(app.requests.length, 2, 'A second queued click must not start another refresh');
    app.respondOptions(1);
    await until(() => app.nativeCalls.length === 1, 'native call after stale option refresh');
    assert.equal(app.button.disabled, true);
    assert.deepEqual(Array.from(app.nativeCalls[0].options.publicKey.challenge), Array.from(Buffer.from('challenge-1')));
    await app.completeNative(0);
    await click;
    assert.deepEqual(app.redirects, [CALLBACK]);
  });

  test(mode + ': initial preparation failure recovers with one retry click', async () => {
    const app = harness(mode);
    app.respond(0, { error: '準備に失敗しました' }, 503);
    await until(() => !app.button.disabled, 'failed initial preparation settled');
    assert.match(app.message.textContent, /準備に失敗しました/);
    const retry = app.click();
    assert.equal(app.requests.length, 2);
    assert.equal(app.button.disabled, true);
    app.respondOptions(1);
    await until(() => app.nativeCalls.length === 1, 'native call after successful retry preparation');
    await app.completeNative(0);
    await retry;
    assert.deepEqual(app.redirects, [CALLBACK]);
  });
}

test('double clicks during a native ceremony do not duplicate native or verification calls', async () => {
  const app = harness();
  await app.ready();
  const first = app.click();
  const duplicate = app.click();
  assert.equal(app.nativeCalls.length, 1);
  assert.equal(app.requests.length, 1);
  assert.equal(app.button.disabled, true);
  await app.completeNative(0);
  await Promise.all([first, duplicate]);
  assert.equal(app.requests.filter(request => request.url.endsWith('/verify')).length, 1);
  assert.deepEqual(app.redirects, [CALLBACK]);
});

test('clicks queued during initial preparation reuse the in-flight options request', async () => {
  const app = harness();
  const first = app.click();
  const duplicate = app.click();
  assert.equal(app.requests.length, 1);
  assert.equal(app.nativeCalls.length, 0);
  app.respondOptions(0);
  await until(() => app.nativeCalls.length === 1, 'native call after shared initial preparation');
  await app.completeNative(0);
  await Promise.all([first, duplicate]);
  assert.equal(app.requests.filter(request => request.url.endsWith('/options')).length, 1);
});

test('verification failure prepares fresh options without redirect and preserves the error', async () => {
  const app = harness();
  await app.ready();
  const click = app.click();
  app.nativeCalls[0].resolve(credential('login'));
  await until(() => app.requests.length === 2, 'verification request');
  app.respond(1, { error: 'サーバーで認証を確認できませんでした' }, 400);
  await until(() => app.requests.length === 3, 'preparation following verification failure');
  assert.deepEqual(app.redirects, []);
  assert.equal(app.button.disabled, true);
  assert.match(app.message.textContent, /サーバーで認証を確認できませんでした/);
  app.respondOptions(2);
  await click;
  assert.equal(app.button.disabled, false);
  assert.match(app.message.textContent, /サーバーで認証を確認できませんでした/);
  const retry = app.click();
  assert.equal(app.nativeCalls.length, 2);
  await app.completeNative(1);
  await retry;
  assert.deepEqual(app.redirects, [CALLBACK]);
});

test('failed automatic preparation leaves a usable one-click recovery', async () => {
  const app = harness();
  await app.ready();
  const click = app.click();
  const cancelled = new Error('cancelled');
  cancelled.name = 'NotAllowedError';
  app.nativeCalls[0].reject(cancelled);
  await until(() => app.requests.length === 2, 'automatic options request');
  app.respond(1, { error: '準備に失敗しました' }, 503);
  await click;
  assert.equal(app.button.disabled, false);
  const retry = app.click();
  assert.equal(app.requests.length, 3);
  app.respondOptions(2);
  await until(() => app.nativeCalls.length === 2, 'native call on a retry after preparation failure');
  await app.completeNative(1);
  await retry;
  assert.deepEqual(app.redirects, [CALLBACK]);
});

for (const callback of [
  'https://attacker.example/auth/v1/callback?code=wrong',
  'https://bvfndgjiahjqdlnyygnx.supabase.co/other-path?code=wrong',
  'http://bvfndgjiahjqdlnyygnx.supabase.co/auth/v1/callback?code=wrong',
  'javascript:alert(1)',
]) {
  test('successful verification cannot redirect outside the callback allowlist: ' + callback.split('?')[0], async () => {
    const app = harness();
    await app.ready();
    const click = app.click();
    await app.completeNative(0, callback);
    await until(() => app.requests.length === 3, 'fresh options after rejecting callback URL');
    assert.deepEqual(app.redirects, []);
    app.respondOptions(2);
    await click;
    assert.deepEqual(app.redirects, []);
    assert.equal(app.button.disabled, false);
  });
}

async function assertRestartOnNextClick(app, {
  destinationMode = app.mode, label, messagePattern = /開き直|期限|最初/,
} = {}) {
  assert.equal(app.button.disabled, false);
  assert.equal(app.button.hidden, false, 'The restart action must stay visible');
  assert.equal(app.button.textContent, label || (destinationMode === 'signup' ? '登録画面を開き直す' : 'ログイン画面を開き直す'));
  assert.match(app.message.textContent, messagePattern);
  assert.equal(app.timers.size, 0, 'An expired flow must leave no preparation deadline running');
  const requestCount = app.requests.length;
  const nativeCount = app.nativeCalls.length;
  await app.click();
  assert.equal(app.redirects.length, 1);
  const destination = new URL(app.redirects[0], SITE);
  assert.equal(destination.origin, SITE);
  assert.equal(destination.pathname, '/');
  assert.equal(destination.searchParams.get('auth'), destinationMode);
  assert.ok(destination.searchParams.get('v'), 'Recovery must request a fresh entry page');
  assert.equal(app.requests.length, requestCount, 'Restart navigates instead of retrying the expired API flow');
  assert.equal(app.nativeCalls.length, nativeCount, 'Restart must not open another native ceremony');
  assert.equal(app.button.disabled, true, 'Keep the button disabled while the entry page opens');
  await app.click();
  assert.equal(app.redirects.length, 1, 'Queued duplicate clicks must not repeat the restart');
}

for (const mode of ['login', 'signup']) {
  test(mode + ': initial options 403 offers a fresh entry flow instead of another POST', async () => {
    const app = harness(mode);
    app.respond(0, { error: '認証を完了できませんでした' }, 403);
    await until(() => !app.button.disabled, 'initial expired-flow response settled');
    assert.equal(app.requests.length, 1);
    assert.equal(app.nativeCalls.length, 0);
    await assertRestartOnNextClick(app);
  });

  test(mode + ': stale options returning 403 stop before native authentication', async () => {
    const app = harness(mode);
    await app.ready();
    app.advanceIdleHour();
    const click = app.click();
    assert.equal(app.requests.length, 2);
    app.respond(1, { error: '認証を完了できませんでした' }, 403);
    await click;
    assert.equal(app.nativeCalls.length, 0);
    assert.equal(app.requests.length, 2);
    await assertRestartOnNextClick(app);
  });

  test(mode + ': verification 403 skips futile preparation and opens a fresh entry flow', async () => {
    const app = harness(mode);
    await app.ready();
    const click = app.click();
    app.nativeCalls[0].resolve(credential(mode));
    await until(() => app.requests.length === 2, 'verification request before 403');
    app.respond(1, { error: '認証を完了できませんでした' }, 403);
    await click;
    assert.equal(app.requests.length, 2, 'Do not automatically prepare against an invalid flow');
    assert.equal(app.requests.filter(request => request.url.endsWith('/options')).length, 1);
    assert.equal(app.nativeCalls.length, 1);
    await assertRestartOnNextClick(app);
  });

  test(mode + ': cancellation followed by options 403 preserves the fresh-flow recovery', async () => {
    const app = harness(mode);
    await app.ready();
    const click = app.click();
    const cancelled = new Error('test cancellation');
    cancelled.name = 'NotAllowedError';
    app.nativeCalls[0].reject(cancelled);
    await until(() => app.requests.length === 2, 'post-cancellation options request');
    app.respond(1, { error: '認証を完了できませんでした' }, 403);
    await click;
    assert.ok(app.requests.every(request => request.url.endsWith('/options')));
    assert.equal(app.requests.length, 2);
    await assertRestartOnNextClick(app);
  });
}

test('a hung options fetch aborts and the next click opens a fresh flow without retrying its challenge', async () => {
  const app = harness();
  assert.equal(app.button.disabled, true);
  assert.equal(app.timers.size, 1);
  const deadline = [...app.timers.values()][0];
  assert.ok(deadline.delay > 0 && deadline.delay <= 20_000, 'Preparation must have a bounded 20-second deadline');
  assert.ok(app.requests[0].init.signal);
  assert.equal(app.requests[0].init.signal.aborted, false);
  app.expireNextTimer();
  await until(() => !app.button.disabled, 'preparation deadline handled');
  assert.equal(app.requests[0].init.signal.aborted, true);
  assert.equal(app.timers.size, 0);
  assert.equal(app.nativeCalls.length, 0);
  assert.deepEqual(app.redirects, []);
  assert.match(app.message.textContent, /時間|接続|応答/);
  await assertRestartOnNextClick(app);
  assert.equal(app.requests.length, 1, 'A late server response must be isolated by starting a new flow');
});

test('preparation deadline remains active until JSON finishes and is then cleared', async () => {
  const app = harness();
  const json = app.respondWithPendingJSON(0);
  await until(() => app.requests[0].jsonReadStarted, 'response JSON reading started');
  assert.equal(app.button.disabled, true);
  assert.equal(app.timers.size, 1, 'Response headers alone must not clear the request deadline');
  json.resolve(publicOptions('login', 0));
  await until(() => !app.button.disabled, 'JSON parsing completed');
  assert.equal(app.timers.size, 0);
  assert.equal(app.requests[0].init.signal.aborted, false);
  const click = app.click();
  app.nativeCalls[0].resolve(credential('login'));
  await until(() => app.requests.length === 2, 'verification begins');
  assert.equal(app.timers.size, 0, 'The verification request has no preparation timeout');
  assert.ok(app.requests[1].init.signal == null, 'Verification must not inherit the preparation AbortController');
  app.respond(1, { redirect_url: CALLBACK });
  await click;
});

test('a hung options JSON body times out and offers a fresh signup flow', async () => {
  const app = harness('signup');
  app.respondWithPendingJSON(0);
  await until(() => app.requests[0].jsonReadStarted, 'stalled JSON reading started');
  app.expireNextTimer();
  await until(() => !app.button.disabled, 'JSON deadline handled');
  assert.equal(app.timers.size, 0);
  assert.equal(app.requests[0].init.signal.aborted, true);
  assert.match(app.message.textContent, /時間|接続|応答/);
  assert.equal(app.nativeCalls.length, 0);
  await assertRestartOnNextClick(app);
  assert.equal(app.requests.length, 1);
});

for (const outcome of ['network failure', 'HTTP 503', 'HTTP 200 without redirect']) {
  test('signup: uncertain verification (' + outcome + ') recovers through login without registering again', async () => {
    const app = harness('signup');
    await app.ready();
    const click = app.click();
    app.nativeCalls[0].resolve(credential('signup'));
    await until(() => app.requests.length === 2, 'signup verification request sent');
    if (outcome === 'network failure') {
      app.requests[1].reject(new Error('Simulated connection loss after request submission'));
    } else if (outcome === 'HTTP 503') {
      app.respond(1, { error: '一時的に確認できませんでした' }, 503);
    } else {
      app.respond(1, { verified: true });
    }
    await click;
    assert.equal(app.requests.length, 2, 'An ambiguous committed registration must never auto-prepare or replay');
    assert.equal(app.nativeCalls.length, 1);
    assert.deepEqual(app.redirects, []);
    await assertRestartOnNextClick(app, {
      destinationMode: 'login', label: '保存したパスキーでログイン', messagePattern: /確認|結果/,
    });
  });
}

test('signup: definitive HTTP 400 still prepares for another registration attempt', async () => {
  const app = harness('signup');
  await app.ready();
  const click = app.click();
  app.nativeCalls[0].resolve(credential('signup'));
  await until(() => app.requests.length === 2, 'signup verification request');
  app.respond(1, { error: '署名を確認できませんでした' }, 400);
  await until(() => app.requests.length === 3, 'fresh registration options after definitive rejection');
  assert.equal(app.requests[2].url, '/auth/passkey/registration/options');
  app.respondOptions(2);
  await click;
  assert.equal(app.button.textContent, app.initialLabel);
  assert.equal(app.button.disabled, false);
  assert.deepEqual(app.redirects, []);
  const retry = app.click();
  assert.equal(app.nativeCalls.length, 2);
  assert.equal(app.nativeCalls[1].method, 'create');
  await app.completeNative(1);
  await retry;
  assert.deepEqual(app.redirects, [CALLBACK]);
});

test('signup: a serialization failure before verification does not suggest an account was created', async () => {
  const app = harness('signup');
  await app.ready();
  const click = app.click();
  const invalid = credential('signup');
  invalid.getClientExtensionResults = () => { throw new Error('Test serialization failure'); };
  app.nativeCalls[0].resolve(invalid);
  await until(() => app.requests.length === 2, 'preparation after local serialization failure');
  assert.ok(app.requests.every(request => request.url.endsWith('/registration/options')));
  app.respondOptions(1);
  await click;
  assert.equal(app.button.disabled, false);
  assert.equal(app.button.textContent, app.initialLabel);
  assert.deepEqual(app.redirects, []);
});

for (const outcome of ['network failure', 'HTTP 503']) {
  test('login: verification ' + outcome + ' keeps the existing authentication retry behavior', async () => {
    const app = harness('login');
    await app.ready();
    const click = app.click();
    app.nativeCalls[0].resolve(credential('login'));
    await until(() => app.requests.length === 2, 'login verification request');
    if (outcome === 'network failure') app.requests[1].reject(new Error('Simulated connection loss'));
    else app.respond(1, { error: '一時的に確認できませんでした' }, 503);
    await until(() => app.requests.length === 3, 'fresh authentication options after login failure');
    assert.equal(app.requests[2].url, '/auth/passkey/authentication/options');
    app.respondOptions(2);
    await click;
    assert.equal(app.button.disabled, false);
    assert.equal(app.button.textContent, app.initialLabel);
    assert.deepEqual(app.redirects, []);
  });
}

test('signup entry keeps the exact notice in the central intro after server verification until login is chosen', async () => {
  const app = harness('login', 'signup');
  assert.equal(app.requests[0].url, '/auth/passkey/authentication/options');
  await app.ready();
  assert.equal(app.button.hidden, true);
  const click = app.click();
  assert.equal(app.nativeCalls[0].method, 'get');
  assert.ok(app.introHistory.every(text => !text.includes('アカウントが見つかりました')));
  app.nativeCalls[0].resolve(credential('login'));
  await until(() => app.requests.length === 2, 'verification before existing-account announcement');
  assert.equal(app.requests[1].url, '/auth/passkey/authentication/verify');
  assert.ok(app.introHistory.every(text => !text.includes('アカウントが見つかりました')));
  app.respond(1, { redirect_url: CALLBACK });
  await click;
  assert.equal(app.title.textContent, 'おかえりなさい');
  assert.equal(app.intro.textContent.replace(/\s+/g, ''), '登録済みのアカウントが見つかりました。元のアカウントでログインしてください。');
  assert.equal(app.intro.hidden, false);
  assert.equal(app.button.className, 'kna-btn kna-pk');
  assert.equal(app.message.textContent, '');
  assert.equal(app.button.textContent, '元のアカウントでログイン');
  assert.equal(app.button.hidden, false);
  assert.equal(app.button.disabled, false);
  assert.equal(app.newButton.disabled, true);
  assert.ok(Object.values(app.sections).every(element => element.hidden));
  assert.equal(app.timers.size, 0);
  app.advanceTimersBy(1000);
  app.clickNew();
  assert.deepEqual(app.redirects, [], 'The confirmed account screen must not automatically disappear');
  await app.click();
  assert.deepEqual(app.redirects, [CALLBACK]);
  assert.equal(app.nativeCalls.length, 1, 'Continuing must not ask for another native ceremony');
  assert.equal(app.requests.length, 2);
  await app.click();
  app.clickNew();
  assert.deepEqual(app.redirects, [CALLBACK], 'Continue can navigate only once');
});

test('a hidden confirmed-account page waits for the member instead of logging in automatically', async () => {
  const app = harness('login', 'signup');
  await app.ready();
  const click = app.click();
  app.setVisibility('hidden');
  await app.completeNative(0);
  await click;
  assert.deepEqual(app.redirects, []);
  assert.equal(app.button.disabled, false);
  app.setVisibility('visible');
  await app.click();
  assert.deepEqual(app.redirects, [CALLBACK]);
  assert.equal(app.timers.size, 0);
});

for (const elapsed of [44999, 45000, 60 * 60 * 1000]) {
  test('confirmed-account continuation checks code age on click after ' + elapsed + 'ms', async () => {
    const app = harness('login', 'signup');
    await app.ready();
    const click = app.click();
    await app.completeNative(0);
    await click;
    app.setVisibility('hidden');
    app.advanceTimersBy(elapsed);
    app.setVisibility('visible');
    assert.deepEqual(app.redirects, []);
    assert.ok(app.intro.textContent.includes('アカウントが見つかりました'));
    await app.click();
    assert.deepEqual(app.redirects, [elapsed < 45000 ? CALLBACK : '/?auth=login&v=20260912-confirmed']);
    assert.equal(app.nativeCalls.length, 1);
    assert.equal(app.requests.length, 2);
    app.clickNew();
    assert.equal(app.redirects.length, 1);
  });
}

test('the continuation window starts before verification so a slow response cannot renew an old code', async () => {
  const app = harness('login', 'signup');
  await app.ready();
  const click = app.click();
  app.nativeCalls[0].resolve(credential('login'));
  await until(() => app.requests.length === 2, 'verification request');
  app.advanceTimersBy(46000);
  app.respond(1, { redirect_url: CALLBACK });
  await click;
  assert.ok(app.intro.textContent.includes('アカウントが見つかりました'));
  await app.click();
  assert.deepEqual(app.redirects, ['/?auth=login&v=20260912-confirmed']);
  assert.equal(app.requests.length, 2);
});

test('navigation failure preserves the confirmed account and never restarts verification or registration', async () => {
  const app = harness('login', 'signup', { navigationFailures: 1 });
  await app.ready();
  const click = app.click();
  await app.completeNative(0);
  await click;
  await app.click();
  assert.deepEqual(app.redirects, []);
  assert.equal(app.button.disabled, false);
  assert.equal(app.button.textContent, '元のアカウントでログイン');
  assert.equal(app.newButton.disabled, true);
  assert.ok(app.intro.textContent.includes('アカウントが見つかりました'));
  app.clickNew();
  assert.equal(app.requests.length, 2);
  assert.equal(app.nativeCalls.length, 1);
  await app.click();
  assert.deepEqual(app.redirects, [CALLBACK]);
});

test('only an explicit new-account action navigates to registration, once', async () => {
  const app = harness('login', 'signup');
  await app.ready();
  assert.deepEqual(app.redirects, []);
  app.clickNew();
  app.clickNew();
  await app.click();
  assert.equal(app.redirects.length, 1);
  const destination = new URL(app.redirects[0]);
  assert.equal(destination.origin, SITE);
  assert.equal(destination.pathname, '/auth/passkey/authorize');
  assert.equal(destination.searchParams.get('screen_hint'), 'signup_new');
  assert.equal(destination.searchParams.get('state'), 'active-state');
  assert.equal(destination.searchParams.get('code_challenge'), 'active-challenge');
  assert.equal(app.nativeCalls.length, 0, 'Navigation must not create a credential in the check page');
  assert.equal(app.requests.length, 1);
  assert.equal(app.button.disabled, true);
  assert.equal(app.newButton.disabled, true);
});

test('new-account action cannot replace the flow during preparation, native login, verification or redirect', async () => {
  const app = harness('login', 'signup');
  app.clickNew();
  assert.deepEqual(app.redirects, []);
  await app.ready();
  const click = app.click();
  assert.equal(app.newButton.disabled, true);
  app.clickNew();
  assert.deepEqual(app.redirects, []);
  app.nativeCalls[0].resolve(credential('login'));
  await until(() => app.requests.length === 2, 'existing-account verification');
  app.clickNew();
  assert.deepEqual(app.redirects, []);
  app.respond(1, { redirect_url: CALLBACK });
  await click;
  app.clickNew();
  assert.deepEqual(app.redirects, []);
  await app.click();
  app.clickNew();
  assert.deepEqual(app.redirects, [CALLBACK]);
  assert.equal(app.nativeCalls.length, 1);
  assert.equal(app.requests.length, 2);
});

for (const outcome of ['cancel', 'verification rejection']) {
  test('signup entry ' + outcome + ' never automatically registers a new account', async () => {
    const app = harness('login', 'signup');
    await app.ready();
    const click = app.click();
    let optionsIndex;
    if (outcome === 'cancel') {
      const error = new Error('Cancelled');
      error.name = 'NotAllowedError';
      app.nativeCalls[0].reject(error);
      optionsIndex = 1;
    } else {
      app.nativeCalls[0].resolve(credential('login'));
      await until(() => app.requests.length === 2, 'existing credential verification');
      app.respond(1, { error: '認証を確認できませんでした' }, 400);
      optionsIndex = 2;
    }
    await until(() => app.requests.length === optionsIndex + 1, 'authentication retry preparation');
    app.clickNew();
    assert.deepEqual(app.redirects, []);
    assert.equal(app.newButton.disabled, true);
    app.respondOptions(optionsIndex);
    await click;
    assert.equal(app.newButton.disabled, false);
    assert.ok(app.requests.every(request => request.url.includes('/authentication/')));
    assert.ok(app.nativeCalls.every(call => call.method === 'get'));
    assert.deepEqual(app.redirects, []);
    assert.ok(app.introHistory.every(text => !text.includes('アカウントが見つかりました')), 'Failure must never announce an existing account');
    if (outcome === 'cancel') assert.match(app.message.textContent, /登録済み|登録時/);
    app.clickNew();
    assert.equal(new URL(app.redirects[0]).searchParams.get('screen_hint'), 'signup_new');
  });
}

for (const outcome of ['403', 'timeout']) {
  test('signup entry ' + outcome + ' disables new registration until a fresh entry flow', async () => {
    const app = harness('login', 'signup');
    if (outcome === '403') app.respond(0, { error: '期限切れ' }, 403);
    else app.expireNextTimer();
    await until(() => !app.button.disabled, 'fresh entry recovery ready');
    assert.equal(app.newButton.disabled, true);
    app.clickNew();
    assert.deepEqual(app.redirects, []);
    await assertRestartOnNextClick(app, { destinationMode: 'signup' });
    assert.equal(app.nativeCalls.length, 0);
  });
}

for (const newURL of [
  'https://attacker.example/auth/passkey/authorize?screen_hint=signup_new',
  '/other-path?screen_hint=signup_new',
  '/auth/passkey/authorize?screen_hint=signup',
  'javascript:alert(1)',
]) {
  test('explicit registration rejects an invalid destination: ' + newURL, async () => {
    const app = harness('login', 'signup', { newURL });
    await app.ready();
    app.clickNew();
    assert.deepEqual(app.redirects, []);
    assert.equal(app.nativeCalls.length, 0);
    assert.equal(app.button.disabled, false);
    assert.equal(app.newButton.disabled, false);
    assert.match(app.message.textContent, /開けません/);
  });
}

test('unsupported WebAuthn keeps both existing-key and new-account buttons disabled', () => {
  const app = harness('login', 'signup', { supported: false });
  assert.equal(app.button.disabled, true);
  assert.equal(app.newButton.disabled, true);
  assert.equal(app.requests.length, 0);
  assert.equal(app.nativeCalls.length, 0);
  assert.match(app.message.textContent, /この環境ではパスキーを利用できません/);
});

for (const outcome of ['unapproved callback', 'missing callback', 'server error']) {
  test('signup entry does not announce an existing account after ' + outcome, async () => {
    const app = harness('login', 'signup');
    await app.ready();
    const click = app.click();
    app.nativeCalls[0].resolve(credential('login'));
    await until(() => app.requests.length === 2, 'verification response to validate');
    if (outcome === 'unapproved callback') app.respond(1, { redirect_url: 'https://attacker.example/auth/v1/callback' });
    else if (outcome === 'missing callback') app.respond(1, {});
    else app.respond(1, { error: '認証結果を確認できませんでした' }, 503);
    await until(() => app.requests.length === 3, 'authentication retry after invalid result');
    app.respondOptions(2);
    await click;
    assert.ok(app.introHistory.every(text => !text.includes('アカウントが見つかりました')));
    assert.equal(app.timers.size, 0, 'Invalid verification results must not schedule a success announcement');
    assert.deepEqual(app.redirects, []);
    assert.ok(app.nativeCalls.every(call => call.method === 'get'));
    assert.ok(app.requests.every(request => request.url.includes('/authentication/')));
  });
}
